[FIX] l10n_de: xmlrpc call can't get account.move
Current behaviour:
When making a xmlrpc call without fields using:
models.execute_kw(
    db,
    uid,
    password,
    'account.move',
    'search_read',
    [[['name', '=', "INV/2023/00001"]]])
the client receives a traceback ending with:
TypeError: cannot marshal<class \'odoo.api.res.partner\'> objects\n'>

Steps to reproduce:
1. install any of the l10n_de_... modules
2. Make a xmlrpc call like stated above
3. Traceback like stated above

Cause of the issue:
The field l10n_de_addresses is used to store
(_("Invoicing Address:"), record.partner_id)
Which isn't serialized correctly:
record.partner_id is not repr
(is python object instead of (6, 'something'))

Fix:
Applied a fix similar to https://github.com/odoo/odoo/commit/602b3f3d39db29fbcd90e3f734bdcc73e67f175d

opw-3248887

closes odoo/odoo#137151

Signed-off-by: Cedric Snauwaert <csn@odoo.com>
Co-authored-by: Julien Castiaux <juc@odoo.com>