[FIX] purchase_stock: ignore the receipt of returned qty
In some cases, the received qty of the POL is incorrect

To reproduce the issue:
1. Create and confirm a PO
2. Receive the product
3. Return the product:
   - Update quantities on SO/PO: False
4. Receive again ("return the return"):
   - Update quantities on SO/PO: False
5. Open the PO

Error: The received qty of the POL is incorrect, it includes the
second receipt

The second receipt is processed as a classic receipt, so we simply
add the done qty of the SM to the received qty of the POL. We have
to improve the conditions.

OPW-3483449

closes odoo/odoo#138480

Signed-off-by: Tiffany Chang (tic) <tic@odoo.com>